### ISSUE TITLE
Adding top-level attributes

### ISSUE THREAD

**Issue by bputt** [census-instrumentation/opencensus-java#1331] opened 2018-07-20 01:45 UTC
Feature request:
It'd be beneficial to set a default set of attributes for the entire trace that would get applied when the spans are built in the exporters.

Let's say the receiving system interacts with an attribute X and each system that sends the trace has to send X with some value. Each system can utilize a default (configured upfront) and or specify a value for X within any span where applicable.

**Comment by songy23** [comment] 2019-03-13 23:04
Duplicate of https://github.com/census-instrumentation/opencensus-java/issues/1633.

**Closed by songy23** 2019-03-13 23:04 UTC
Labels: enhancement, feature request, tracing
