### ISSUE TITLE
Build failures: "Undefined reference" from animal-sniffer

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-java#538] opened 2017-08-22 21:30 UTC
I am getting this error consistently without modifying the agent code:

/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest$1.class:67: Undefined reference: io.grpc.Context io.grpc.Context.current()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest$1.class:68: Undefined reference: Object io.grpc.Context.Key.get()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest$2.class:96: Undefined reference: io.grpc.Context io.grpc.Context.current()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest$2.class:97: Undefined reference: Object io.grpc.Context.Key.get()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest$3.class:119: Undefined reference: io.grpc.Context io.grpc.Context.current()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest$3.class:120: Undefined reference: Object io.grpc.Context.Key.get()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest$4.class:141: Undefined reference: io.grpc.Context io.grpc.Context.current()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest$4.class:141: Undefined reference: io.grpc.Context io.grpc.Context.ROOT
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest$4.class:142: Undefined reference: io.grpc.Context io.grpc.Context.current()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest$4.class:143: Undefined reference: Object io.grpc.Context.Key.get()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest.class:51: Undefined reference: io.grpc.Context io.grpc.Context.current()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest.class:51: Undefined reference: void io.grpc.Context.detach(io.grpc.Context)
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest.class:58: Undefined reference: io.grpc.Context io.grpc.Context.current()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest.class:58: Undefined reference: io.grpc.Context io.grpc.Context.withValue(io.grpc.Context.Key, Object)
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest.class:59: Undefined reference: io.grpc.Context io.grpc.Context.attach()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest.class:87: Undefined reference: io.grpc.Context io.grpc.Context.current()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest.class:87: Undefined reference: io.grpc.Context io.grpc.Context.withValue(io.grpc.Context.Key, Object)
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest.class:88: Undefined reference: io.grpc.Context io.grpc.Context.attach()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest.class:110: Undefined reference: io.grpc.Context io.grpc.Context.current()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest.class:110: Undefined reference: io.grpc.Context io.grpc.Context.withValue(io.grpc.Context.Key, Object)
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest.class:111: Undefined reference: io.grpc.Context io.grpc.Context.attach()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest.class:131: Undefined reference: io.grpc.Context io.grpc.Context.current()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest.class:131: Undefined reference: io.grpc.Context io.grpc.Context.withValue(io.grpc.Context.Key, Object)
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest.class:132: Undefined reference: io.grpc.Context io.grpc.Context.attach()
/Users/bdrutu/github/instrumentation-java/contrib/agent/build/classes/java/test/io/opencensus/contrib/agent/ExecutorInstrumentationTest.class:39: Undefined reference: io.grpc.Context.Key io.grpc.Context.key(String)

**Comment by ubschmidt2** [comment] 2017-08-23 06:06
Not sure yet what's going on. Could you put the full output into a Gist?

**Comment by ubschmidt2** [comment] 2017-08-23 06:41
Could not reproduce yet. :-(

**Comment by ubschmidt2** [comment] 2017-08-23 13:33
This is not from javac and not from the actual test execution, but from some tool in between, not sure which.

**Comment by ubschmidt2** [comment] 2017-08-23 14:28
Could be from https://github.com/mojohaus/animal-sniffer/blob/ca55e4f4462a92fd17ea143469adc32b94b5147b/animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/SignatureChecker.java#L565.

**Comment by ubschmidt2** [comment] 2017-08-25 21:41
AFAICT, these messages come from animal sniffer, and it looks like an issue with the classpath that animal sniffer is using (grpc-context not on classpath?). What's puzzling is that this is a different permanent failure than described in the other bugs. Have you seen these "undefined reference" errors from animal sniffer lately? If not, I'd suggest to close this issue, and I focus on the other permanent build failure.

**Comment by ubschmidt2** [comment] 2017-08-26 00:04
I'm closing this in favor of https://github.com/census-instrumentation/opencensus-java/issues/557. Same underlying issue. Order of task execution in gradle.

**Closed by ubschmidt2** 2017-08-26 00:04 UTC
Labels: agent, bug, build
