### ISSUE TITLE
Get a "com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: Requested entity was not found." when using Stackdriver Exporter with Google Cloud

### ISSUE THREAD

**Issue by johanhaleby** [census-instrumentation/opencensus-java#1184] opened 2018-05-08 14:34 UTC
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?

0.13.1

### What JVM are you using (`java -version`)?
Java 1.8.0_144

### What did you do?
I just want to get started with open census with stackdriver exporting.

I've created a trace like this:

```java
StackdriverTraceExporter.createAndRegister(StackdriverTraceConfiguration.builder().setProjectId("projectId").build());

Span rootSpan = Tracing.getTracer().spanBuilder("Something").setSampler(Samplers.alwaysSample()).startSpan();
// Some code

rootSpan.end();
```

### What did you expect to see?
No exceptions

### What did you see instead?
```java
[server] 2018-05-08 14:27:14,169 [ExportComponent.ServiceExporterThread-0] WARN  io.opencensus.trace.export.ExportComponent  - Exception thrown by the service export io.opencensus.exporter.trace.stackdriver.StackdriverTraceExporter
[server] com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: Requested entity was not found.
[server] at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:45)
[server] at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
[server] at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
[server] at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:95)
[server] at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:61)
[server] at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1341)
[server] at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
[server] at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1025)
[server] at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
[server] at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
[server] at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:492)
[server] at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:467)
[server] at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
[server] at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
[server] at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
[server] at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
[server] at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
[server] at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
[server] at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
[server] at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
[server] at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
[server] at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
[server] at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
[server] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[server] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[server] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[server] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[server] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[server] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[server] at java.lang.Thread.run(Thread.java:745)
[server] Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Requested entity was not found.
[server] at io.grpc.Status.asRuntimeException(Status.java:526)
[server] ... 19 more
```

I'm using the following dependencies:

```xml
  <dependency>
    <groupId>io.opencensus</groupId>
    <artifactId>opencensus-api</artifactId>
    <version>${opencensus.version}</version>
</dependency>
<dependency>
    <groupId>io.opencensus</groupId>
    <artifactId>opencensus-exporter-trace-stackdriver</artifactId>
    <version>${opencensus.version}</version>
</dependency>
<dependency>
    <groupId>io.opencensus</groupId>
    <artifactId>opencensus-impl</artifactId>
    <version>${opencensus.version}</version>
    <scope>runtime</scope>
</dependency>        
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud</artifactId>
    <version>0.42.0-alpha</version>
</dependency>
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>25.0-jre</version>
</dependency>
```

What am I doing wrong?

**Comment by songy23** [comment] 2018-05-08 17:19
Hi @johanhaleby , I just ran the QuickStart example using the Stackdriver trace exporter and it worked fine. My guess is there might be an incompatibility between the `google-cloud` you have in the dependency, and the `google-cloud` we used in Stackdriver trace exporter. Could you try remove the `google-cloud` and run this again?

/cc @bogdandrutu

**Comment by johanhaleby** [comment] 2018-05-08 20:06
Unfortunately we can't remove it since we have other code that depends in this library which doesn't build if we remove it from the classpath. What version _should_ we use?

**Comment by songy23** [comment] 2018-05-08 20:17
For now can you try [0.34.0-beta](https://github.com/census-instrumentation/opencensus-java/blob/master/build.gradle#L160)?

**Comment by johanhaleby** [comment] 2018-05-09 06:31
I've tried with `0.34.0-beta` of `google-cloud-trace` but I also had to add

```xml
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-storage</artifactId>
    <version>1.29.0</version>
</dependency>
```

since we're using Google Cloud Storage in other code. But the problem still persists. These are the relevant dependencies after the change:

```xml
<dependency>
    <groupId>io.opencensus</groupId>
    <artifactId>opencensus-api</artifactId>
    <version>${opencensus.version}</version>
</dependency>
<dependency>
    <groupId>io.opencensus</groupId>
    <artifactId>opencensus-exporter-trace-stackdriver</artifactId>
    <version>${opencensus.version}</version>
</dependency>
<dependency>
    <groupId>io.opencensus</groupId>
    <artifactId>opencensus-exporter-trace-logging</artifactId>
    <version>${opencensus.version}</version>
</dependency>
<dependency>
    <groupId>io.opencensus</groupId>
    <artifactId>opencensus-impl</artifactId>
    <version>${opencensus.version}</version>
    <scope>runtime</scope>
</dependency>
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-trace</artifactId>
    <version>0.34.0-beta</version>
</dependency>
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-storage</artifactId>
    <version>1.29.0</version>
</dependency>
```

**Comment by johanhaleby** [comment] 2018-05-09 06:40
I see this in Stackdriver trace view in the Google Cloud Console:

![image](https://user-images.githubusercontent.com/187029/39799419-70c7bfd4-5364-11e8-9a38-e18399ddf58d.png)

**Comment by songy23** [comment] 2018-05-09 17:14
I didn't see anything wrong from your dependencies. I couldn't reproduce this error on my machine either.

I filed an issue to cloud client to see if they have some better idea on this: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3250.

**Comment by songy23** [comment] 2018-05-09 17:51
I just made a snapshot release. While waiting for the response from cloud client, can you also try update `opencensus` version to `0.14.0-SNAPSHOT` and update `google-cloud` to `0.47.0-beta`, to see if it helps?

**Comment by johanhaleby** [comment] 2018-05-11 05:54
@songy23 Thanks for your support. But where can I find the snapshot release (i.e. which maven repository should I add)?

**Comment by johanhaleby** [comment] 2018-05-16 06:49
Unfortunately there's still the same exception when using `0.14.0-SNAPSHOT`:

```java
2018-05-16 06:47:15,036 [ExportComponent.ServiceExporterThread-0] WARN  io.opencensus.trace.export.ExportComponent  - Exception thrown by the service export io.opencensus.exporter.trace.stackdriver.StackdriverTraceExporter
com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: Requested entity was not found.
at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:45)
at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:95)
at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:61)
at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1341)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1025)
at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:492)
at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:467)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Requested entity was not found.
at io.grpc.Status.asRuntimeException(Status.java:526)
... 19 more
```

Is there perhaps different versions of the strackdriver API and we've enabled the wrong one on GCP?

**Comment by songy23** [comment] 2018-05-16 16:52
That's one possibility, please note our trace exporter uses the [V2 SD trace client](https://cloud.google.com/trace/docs/reference/v2/rest/).

Per https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3250 this error is probably propagated from backend (rather than an error on client library), so I guess changing the `google-cloud` version won't help in this case.

**Comment by songy23** [comment] 2018-05-16 17:14
Besides, please make sure you have all the [prerequisites](https://github.com/census-instrumentation/opencensus-java/tree/master/exporters/trace/stackdriver#prerequisites).

I'll also ask people on Stackdriver Trace backend on this.

**Comment by johanhaleby** [comment] 2018-05-17 06:28
From what I understand we are using the V2 SD API. And I've also tried to accommodate the prerequisites to the best of my ability, but it's quite possible that I could have misunderstood something.

**Comment by songy23** [comment] 2018-05-17 18:31
Hi @johanhaleby , can you try [adding the trace.append OAuth scope to k8s cluster](https://cloud.google.com/trace/docs/setup/java#kubernetes_engine)?

**Comment by songy23** [comment] 2018-05-18 16:18
Thanks, I'll share this information with the backend team to help debug.

**Comment by johanhaleby** [comment] 2018-05-21 06:29
Thanks a lot for your help. The problem was that I had been using a project id with a trailing space which was really hard to spot. But after fixing this I run into another issue:

```java
May 21, 2018 6:24:06 AM io.opencensus.implcore.trace.export.SpanExporterImpl$Worker onBatchExport
WARNING: Exception thrown by the service export io.opencensus.exporter.trace.stackdriver.StackdriverTraceExporter
java.lang.VerifyError: Bad type on operand stack
Exception Details:
Location:
com/google/api/AnnotationsProto.registerAllExtensions(Lcom/google/protobuf/ExtensionRegistryLite;)V @4: invokevirtual
Reason:
Type 'com/google/protobuf/GeneratedMessage$GeneratedExtension' (current frame, stack[1]) is not assignable to 'com/google/protobuf/
Current Frame:
bci: @4
flags: { }
locals: { 'com/google/protobuf/ExtensionRegistryLite' }
stack: { 'com/google/protobuf/ExtensionRegistryLite', 'com/google/protobuf/GeneratedMessage$GeneratedExtension' }
Bytecode:
0x0000000: 2ab2 0003 b600 04b1

at com.google.devtools.cloudtrace.v2.TraceProto.<clinit>(TraceProto.java:198)
at com.google.devtools.cloudtrace.v2.Span$Attributes$AttributeMapDefaultEntryHolder.<clinit>(Span.java:443)
at com.google.devtools.cloudtrace.v2.Span$Attributes$Builder.internalGetMutableAttributeMap(Span.java:925)
at com.google.devtools.cloudtrace.v2.Span$Attributes$Builder.putAttributeMap(Span.java:1079)
at io.opencensus.exporter.trace.stackdriver.StackdriverV2ExporterHandler.toAttributesProto(StackdriverV2ExporterHandler.java:227)
at io.opencensus.exporter.trace.stackdriver.StackdriverV2ExporterHandler.generateSpan(StackdriverV2ExporterHandler.java:135)
at io.opencensus.exporter.trace.stackdriver.StackdriverV2ExporterHandler.export(StackdriverV2ExporterHandler.java:338)
at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.onBatchExport(SpanExporterImpl.java:138)
at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.run(SpanExporterImpl.java:187)
at java.lang.Thread.run(Thread.java:745)
```

Using 0.13.2 of opencensus and 0.47.0-beta of google-cloud-trace. Should I open a new issue for this?

**Comment by songy23** [comment] 2018-05-21 16:39
This error seems to be related to [putting agent attribute](https://github.com/census-instrumentation/opencensus-java/commit/a1a6cf16ec5e6ec3c1e08e96b1e8dd9a45dce13e#diff-2f7e8b7487a68c644aef32903d35ca13R227):

```java
attributesBuilder.putAttributeMap(AGENT_LABEL_KEY, AGENT_LABEL_VALUE);
```

@bogdandrutu do you have any idea on this?

**Comment by sebright** [comment] 2018-05-21 17:42
That looks like an unrelated error, so I'll open a new issue.

**Comment by sebright** [comment] 2018-05-21 17:45
Closing, since it sounds like the first issue was resolved.  I opened #1204 for the second issue.

**Closed by sebright** 2018-05-21 17:45 UTC
Labels: bug, exporters, tracing
